site_name: SỐNG BỀN VỮNG
# repo_url: https://github.com/earthknowsbest/sustainable-living
site_author: Peace Vegan School
site_description: >-
  Sống bền vững tập hợp kinh nghiệm sống, sách, báo cáo và nghiên cứu về đời sống con người trên trái đất, cung cấp cái nhìn toàn diện về hệ sinh thái, những phương thức sống bền vững, bảo tồn và khôi phục tự nhiên.

# customed port of serving
dev_addr: '127.0.0.1:9000'
nav:
  # - Home: index.md
  - Sinh thái:
    - Hiến chương: ecology/sobriete.md
    - Khủng hoảng: ecology/bio-crisis.md
    - Đa dạng sinh học: ecology/biodiversity.md
    - Nương vào tự nhiên: ecology/nature-interdependence.md
    - Cây cỏ Việt Nam: ecology/viet-plants.md
    - Vườn rừng: ecology/forest-garden.md
    - Permaculture:
      - Giới thiệu: ecology/permaculture/perma-intro.md
      - Đạo đức & Nguyên lý: ecology/permaculture/perma-moral.md
      - Lợi ích: ecology/permaculture/perma-why.md
      - Nông trại thực tế: ecology/permaculture/perma-farms.md
      - Nông trại trường Peace & những người bạn: ecology/permaculture/perma-farms-2.md
      - Hướng dẫn: ecology/permaculture/perma-guide.md
    # - Nông nghiệp:
  #   - Navdana: ecology/navdana.md
  #   - Tương lai farm nhỏ: ecology/small-farm-future.md
  - Khí hậu:
    - Nhiệt độ & CO₂: overview/climate.md
    - Cảnh báo 2024: overview/climate-2024.md
    - Cảnh báo 2023: overview/climate-2023.md
    - Tương lai kinh hoàng: overview/ghastly-future.md
    - Dân số & 4ºC: overview/population-crisis.md
    - Biến đổi khí hậu: 
      - Báo cáo năm 2021:
        - overview/climate-change/climate-reality/index.md
        - Thực trạng (1 → 12): overview/climate-change/climate-reality/reality-1.md
        - Rủi ro lớn (13 → 15): overview/climate-change/climate-reality/reality-2.md
        - Hành động (16 → 20): overview/climate-change/climate-reality/reality-3.md
        - Tổng hợp: overview/climate-change/climate-reality/reality-4.md
      - Việt Nam:
        - Báo cáo quốc gia 2022: overview/climate-change/vietnam/national-report.md
  - Năng lượng:
    - Năng lượng & Sự sống: 
      - energy/index.md 
      - Khát vọng con người: 
        - 1. Tăng trưởng: energy/human-ambition/1-growth.md
        - 2. Kinh tế: energy/human-ambition/2-econ.md
        - 3. Dân số: energy/human-ambition/3-population.md
        - 4. Không gian: energy/human-ambition/4-space.md
        - 5. Đơn vị: energy/human-ambition/5-energy-unit.md
        - 6. Nhiệt năng: energy/human-ambition/6-thermal.md
        - 7. Bối cảnh: energy/human-ambition/7-landscape.md
        - 8. Nhiên liệu (I): energy/human-ambition/8-fossil-I.md
        - 8. Hoá thạch (II): energy/human-ambition/8-fossil-II.md
        - 9. Biến đổi (I): energy/human-ambition/9-climate-I.md
        - 9. Khí hậu (II): energy/human-ambition/9-climate-II.md
    - Năng lượng tái tạo: 
      - Hoài nghi °1: energy/renewables/renewable-skeptics.md
      - Hoài nghi °2: energy/renewables/renewable-skeptics-2.md
      - Hiệu quả năng lượng: energy/renewables/energy-efficiency.md
  - Kinh tế:
    - Xã hội hữu cơ: economics/superorganism.md
    - Địa phương hoá: economics/localization.md
    - Tăng trưởng xanh: economics/green-growth.md
    - Phật giáo: economics/buddhist-econ.md
    # - Kinh tế xã hội: economics/why-socialism.md
    - Kinh tế Phật giáo: 
      - Giới thiệu: economics/buddhist/intro.md
      - Hạn chế: economics/buddhist/limitations.md
      - Đặc điểm: economics/buddhist/characteristics.md
      - Tổng kết: economics/buddhist/summary.md
      - Trung Đạo: economics/buddhist/middle-way.md
      # - Chương 2: economics/buddhist/chap-2.md
    - Cái giá phải trả: 
      - Giới thiệu: economics/expenses/intro.md
      - Lịch sử: economics/expenses/history.md
    - Phản tăng trưởng:
      - Khái niệm: economics/degrowth/intro.md
  #     - economics/degrowth/decoupling.md
  #     - economics/degrowth/beyondgrowth.md
  #     - economics/degrowth/solution.md
    - Kinh tế học Doughnut:
      - Khái niệm: economics/donut/doughnut.md
      - Tư duy kinh tế: economics/donut/donut-thinking.md
  #   - “Nhỏ thì đẹp”: economics/small-is-beautiful.md
  - Vegan:
    - Vegan là gì: vegan/intro.md
    - Chế độ lành mạnh: vegan/food-lancet.md
    - Tại sao ăn thuần chay: 
      - Lựa chọn tốt nhất: vegan/why-vegan/vegan-choice.md
      - Phúc lợi động vật: vegan/why-vegan/animals-killed.md
      - Môi trường sống: vegan/why-vegan/environment.md
      - 30 Lời bào chữa: 
        - vegan/why-vegan/excuses/index.md
        - Lý do 1-5: vegan/why-vegan/excuses/excuses-1-5.md
        - Lý do 6-10: vegan/why-vegan/excuses/excuses-6-10.md
        - Lý do 11-15: vegan/why-vegan/excuses/excuses-11-15.md
        - Lý do 16-20: vegan/why-vegan/excuses/excuses-16-20.md
        - Lý do 21-25: vegan/why-vegan/excuses/excuses-21-25.md
        - Lý do 26-30: vegan/why-vegan/excuses/excuses-26-30.md
      - Phim tài liệu: vegan/why-vegan/documentaries.md
  - Low-tech:
    - Khái quát:
      - Giới thiệu: lowtech/overview/intro.md
      - Lo-TEK: lowtech/overview/lo-tek.md
      - Nhật Bản thời Edo I: lowtech/overview/edo-japan-I.md
      - Nhật Bản thời Edo II: lowtech/overview/edo-japan-II.md
    - Sinh khối:
      - Than sinh học I: lowtech/biomass/biochar-I.md
      - Than sinh học II: lowtech/biomass/biochar-II.md
      - Bếp ĐK-T5: lowtech/biomass/dk-t5.md
    - Năng lượng mặt trời:
      # - Lời mở đầu: lowtech/solar/manifesto.md
      - Bếp mặt trời I: lowtech/solar/solar-cook-I.md
      - Bếp mặt trời II: lowtech/solar/solar-cook-II.md
      - Bếp mặt trời III: lowtech/solar/solar-cook-III.md
  #   - Nước ngọt:
  #     - Chiết suất: lowtech/water/water-air.md
  #     - Lọc nước °1: lowtech/water/water-purify/water-purify-1.md
  #     - Lọc nước °2: lowtech/water/water-purify/water-purify-2.md
  #     - Lọc nước °3: lowtech/water/water-purify/water-purify-3.md
  #   - Bơm nước: lowtech/water/water-pump.md
  - Sáng kiến:
    # - Sinh quyển: 
    - Nửa Trái Đất: earth/half-earth.md
    - 30 × 30: earth/30by30.md
    - Hiệp ước: earth/fossil-treaty.md
    - Người bản địa: earth/indigenous.md
    - Dừng bay: earth/staygrounded.md
    - Xã hội bền vững:
      - Nhật Bản thời Edo:
        - earth/society/index.md 
        - Mặt trời & dầu mỏ: earth/society/edo/chap-1.md
        - Mặt tối sự tiện lợi: earth/society/edo/chap-2.md
        - Đường đất: earth/society/edo/chap-3.md
        - Sống thuận tự nhiên: earth/society/edo/chap-4.md
        - Mặt trời & rừng: earth/society/edo/chap-5.md
        - Biết đủ: earth/society/edo/chap-6.md
        - Bắt đầu từ từ: earth/society/edo/chap-7.md
        - Nguyên tắc Nishiki-e: earth/society/edo/chap-8.md
        - Vòng đời yukata: earth/society/edo/chap-9a.md
        - Lời nguyền: earth/society/edo/chap-9b.md
        - Có cần tăng trưởng?: earth/society/edo/chap-9c.md
        - Dễ sửa chữa: earth/society/edo/chap-9d.md
        - Tái sử dụng: earth/society/edo/chap-9e.md
        - Đa dạng địa phương: earth/society/edo/chap-10.md
        - Giá trị nỗ lực: earth/society/edo/chap-11.md
        - Từ ngoài vào trong: earth/society/edo/chap-12.md
        - Hệ quả: earth/society/edo/chap-13.md  
        - Nhận diện sai lầm: earth/society/edo/chap-14.md
  #     - Đại dương: earth/biosphere/ocean.md
  #   - Cộng đồng:
  #     - Phong trào: earth/community/movements.md
  #     - Người dân tộc: earth/community/native.md
  #     - Dự án Drawdown: earth/community/drawdown.md
  #     - Đoàn kết: earth/community/solidarity.md
  #   - Cá nhân:
  #     - Thực phẩm: earth/personal/food.md
  #     - Phụ nữ: earth/personal/women.md
  #     - Giao thông: earth/personal/transport.md
  #     - Tài nguyên: earth/personal/material.md
  #     - Thành phố: earth/personal/city.md
  - Nhân sinh:
    - Lịch sử:
      - Văn minh:
        - Các điều kiện: human/history/civilization/conditions.md 
        - Kinh tế: human/history/civilization/economics.md 
        - Chính trị: human/history/civilization/politics.md 
        - Đạo đức I & II: human/history/civilization/morals-I-II.md 
        - Đạo đức III & IV: human/history/civilization/morals-III-IV.md
    - Tinh thần: 
      - Đạo Phật:
        - Nói với tuổi trẻ: human/spirituality/buddha/intro.md
        - Thực tập: human/spirituality/buddha/practice.md
        - Tâm kinh: human/spirituality/buddha/tamkinh.md
        - Pháp Hoa (I): human/spirituality/buddha/lotus-I.md
        - Pháp Hoa (II): human/spirituality/buddha/lotus-II.md
        - Thơ văn thiền (I): human/spirituality/buddha/poem-I.md
      - Đạo Lão—Trang:
        - Giản lược (I): human/spirituality/lao-trang/summary-I.md
        - Giản lược (II): human/spirituality/lao-trang/summary-II.md
        - Giản lược (III): human/spirituality/lao-trang/summary-III.md
      - Đạo Khổng:
        - Trung Dung: human/spirituality/khong/trungdung.md

  #   - Thể chất: human/body.md
  #   - Dinh dưỡng: human/nutrition.md
  #   - Giấc ngủ: human/sleep.md
  # - Blog:
  #   - Trái đất: blog/earth-value.md
  # - About:
  #   - Liên hệ: about/contact.md
    
theme: 
  name: material
  favicon: assets/images/sun.png
  custom_dir: overrides
  # logo_dark_mode: assets/logo-dark.svg
  # logo_light_mode: assets/logo-light.svg
  language: vi
  font: false
  # font: 
  #   text: Andada Pro
    # text: Source Serif Pro, Fraunces
    # text: Playfair Display
    # text: Noto Serif
    # text: Literata
    # text: Source Serif 4
    # text: Merriweather 
  icon:
    repo: fontawesome/brands/github-alt
    logo: custom/logo
  palette:
    - scheme: default
      # primary: light
      accent: default
      toggle:
        # icon: material/brightness-7
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: slate
      accent: slate
      toggle:
        # icon: material/brightness-2
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - search.suggest
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.tabs
    - navigation.sections
    # - navigation.tabs.sticky
    # - navigation.bottom
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - toc.follow

extra_css: [assets/stylesheets/extra.css]

copyright: Copyright &copy; 2024 Sống Bền Vững

extra:
  generator: false
  # consent:
  #   actions:
  #     - accept
  #     - manage

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - meta
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search:
      # enabled: false
      lang: en
    #   - vi
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox
      auto_caption: false
      caption_position: bottom

watch:
  - .  # reload docs for any file changes
