site_name: SỐNG BỀN VỮNG
# repo_url: https://github.com/earthknowsbest/sustainable-living
site_author: Peace Vegan School
site_description: >-
  Sống bền vững tập hợp kinh nghiệm sống, sách, báo cáo và nghiên cứu về đời sống con người trên trái đất, cung cấp cái nhìn toàn diện về hệ sinh thái, những phương thức sống bền vững, bảo tồn và khôi phục tự nhiên.

# customed port of serving
dev_addr: '127.0.0.1:9000'
nav:
  # - Home: index.md
  - Sinh thái:
    - Hiến chương: ecology/sobriete.md
    - Khủng hoảng: ecology/bio-crisis.md
    - Đa dạng sinh học: ecology/biodiversity.md
    - Nương vào tự nhiên: ecology/nature-interdependence.md
    - Cây cỏ Việt Nam: ecology/viet-plants.md
    - Vườn rừng: ecology/forest-garden.md
    - Permaculture:
      - Giới thiệu: ecology/permaculture/perma-intro.md
      - Đạo đức & Nguyên lý: ecology/permaculture/perma-moral.md
      - Lợi ích: ecology/permaculture/perma-why.md
      - Nông trại thực tế: ecology/permaculture/perma-farms.md
      - Nông trại trường Peace & những người bạn: ecology/permaculture/perma-farms-2.md
      - Hướng dẫn: ecology/permaculture/perma-guide.md
    # - Nông nghiệp:
  #   - Navdana: ecology/navdana.md
  #   - Tương lai farm nhỏ: ecology/small-farm-future.md
  - Khí hậu:
    - Nhiệt độ & CO₂: overview/climate.md
    - Tương lai kinh hoàng: overview/ghastly-future.md
    - Dân số & 4ºC: overview/population-crisis.md
    - Biến đổi khí hậu: 
      - Báo cáo năm 2021:
        - overview/climate-change/climate-reality/index.md
        - Thực trạng (1 → 12): overview/climate-change/climate-reality/reality-1.md
        - Rủi ro lớn (13 → 15): overview/climate-change/climate-reality/reality-2.md
        - Hành động (16 → 20): overview/climate-change/climate-reality/reality-3.md
        - Tổng hợp: overview/climate-change/climate-reality/reality-4.md
      - Việt Nam:
        - Báo cáo quốc gia 2022: overview/climate-change/vietnam/national-report.md
  - Năng lượng:
    - Năng lượng & Sự sống: 
      - energy/index.md 
      - Khát vọng con người: 
        - 1. Tăng trưởng: energy/human-ambition/1-growth.md
        - 2. Kinh tế: energy/human-ambition/2-econ.md
        - 3. Dân số: energy/human-ambition/3-population.md
        - 4. Không gian: energy/human-ambition/4-space.md
        - 5. Đơn vị: energy/human-ambition/5-energy-unit.md
        - 6. Nhiệt năng: energy/human-ambition/6-thermal.md
        - 7. Bối cảnh: energy/human-ambition/7-landscape.md
        - 8. Nhiên liệu (I): energy/human-ambition/8-fossil-I.md
        - 8. Hoá thạch (II): energy/human-ambition/8-fossil-II.md
        # - 9. Khí hậu (I): energy/human-ambition/9-climate-I.md
    - Năng lượng tái tạo: 
      - Hoài nghi °1: energy/renewables/renewable-skeptics.md
      - Hoài nghi °2: energy/renewables/renewable-skeptics-2.md
      - Hiệu quả năng lượng: energy/renewables/energy-efficiency.md
  - Kinh tế:
    - Xã hội hữu cơ: economics/superorganism.md
    - Kinh tế Phật giáo: economics/buddhist-econ.md
    - Địa phương hoá: economics/localization.md
    - Tăng trưởng xanh: economics/green-growth.md
    - Kinh tế xã hội: economics/why-socialism.md
    - Phản tăng trưởng:
      - Khái niệm: economics/degrowth/intro.md
  #     - economics/degrowth/decoupling.md
  #     - economics/degrowth/beyondgrowth.md
  #     - economics/degrowth/solution.md
    - Kinh tế học Doughnut:
      - Khái niệm: economics/donut/doughnut.md
      - Tư duy kinh tế: economics/donut/donut-thinking.md
  #   - “Nhỏ thì đẹp”: economics/small-is-beautiful.md
  - Vegan:
    - Vegan là gì: vegan/intro.md
    - Chế độ lành mạnh: vegan/food-lancet.md
    - Tại sao ăn thuần chay: 
      - Môi trường sống: vegan/why-vegan/environment.md
      - 30 Lời bào chữa: 
        - vegan/why-vegan/excuses/index.md
        - Lý do 1-5: vegan/why-vegan/excuses/excuses-1-5.md
        - Lý do 6-10: vegan/why-vegan/excuses/excuses-6-10.md
        - Lý do 11-15: vegan/why-vegan/excuses/excuses-11-15.md
        - Lý do 16-20: vegan/why-vegan/excuses/excuses-16-20.md
        - Lý do 21-25: vegan/why-vegan/excuses/excuses-21-25.md
        - Lý do 26-30: vegan/why-vegan/excuses/excuses-26-30.md
      - Phim tài liệu: vegan/why-vegan/documentaries.md
  - Low-tech:
    - Năng lượng mặt trời:
      # - Lời mở đầu: lowtech/solar/manifesto.md
      - Bếp mặt trời I: lowtech/solar/solar-cook-I.md
      - Bếp mặt trời II: lowtech/solar/solar-cook-II.md
      - Bếp mặt trời III: lowtech/solar/solar-cook-III.md
  #   - Nước ngọt:
  #     - Chiết suất: lowtech/water/water-air.md
  #     - Lọc nước °1: lowtech/water/water-purify/water-purify-1.md
  #     - Lọc nước °2: lowtech/water/water-purify/water-purify-2.md
  #     - Lọc nước °3: lowtech/water/water-purify/water-purify-3.md
  #   - Bơm nước: lowtech/water/water-pump.md
  # - Chữa Lành Trái Đất:
  #   - Sinh quyển: 
  #     - Một nửa Trái Đất: earth/biosphere/half-earth.md
  #     - Đại dương: earth/biosphere/ocean.md
  #   - Cộng đồng:
  #     - Phong trào: earth/community/movements.md
  #     - Người dân tộc: earth/community/native.md
  #     - Dự án Drawdown: earth/community/drawdown.md
  #     - Đoàn kết: earth/community/solidarity.md
  #   - Cá nhân:
  #     - Thực phẩm: earth/personal/food.md
  #     - Phụ nữ: earth/personal/women.md
  #     - Giao thông: earth/personal/transport.md
  #     - Tài nguyên: earth/personal/material.md
  #     - Thành phố: earth/personal/city.md
  # - Con người:
  #   - Tâm linh: human/spirituality.md
  #   - Thể chất: human/body.md
  #   - Dinh dưỡng: human/nutrition.md
  #   - Giấc ngủ: human/sleep.md
  # - Blog:
  #   - Trái đất: blog/earth-value.md
  # - About:
  #   - Liên hệ: about/contact.md
    
theme: 
  name: material
  custom_dir: overrides
  # logo_dark_mode: assets/logo-dark.svg
  # logo_light_mode: assets/logo-light.svg
  language: vi
  font:
    # text: Source Serif Pro
    # text: Playfair Display
    # text: Noto Serif
    text: Literata
  icon:
    repo: fontawesome/brands/github-alt
    logo: custom/logo
  palette:
    - scheme: default
      # primary: light
      accent: default
      toggle:
        # icon: material/brightness-7
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: slate
      accent: slate
      toggle:
        # icon: material/brightness-2
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.highlight
    # - search.share
    - search.suggest
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.tabs
    - navigation.sections
    # - navigation.tabs.sticky
    # - navigation.bottom
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - toc.follow

extra_css: [stylesheets/extra.css]

copyright: Copyright &copy; 2023 Sống Bền Vững

extra:
  generator: false
  # consent:
  #   actions:
  #     - accept
  #     - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search:
      lang: 
        - en

watch:
  - .  # reload docs for any file changes
