site_name: SỐNG BỀN VỮNG
repo_url: https://github.com/earthknowsbest/sustainable-living
site_author: Peace Vegan School
site_description: >-
  Sống bền vững tập hợp sách báo, nghiên cứu về đời sống 
  con người trên trái đất, cung cấp cái nhìn toàn diện về 
  hệ sinh thái, những phương thức sống bền vững, bảo tồn 
  và khôi phục tự nhiên.

# customed port of serving
dev_addr: '127.0.0.1:9000'
nav:
  - Home: index.md
  - Sinh thái:
    - Sinh thái học: ecology/sinh-thai-hoc.md
    - Năng lượng & Sự sống:
      - Khát vọng con người:
        - ecology/energy/human-ambition/index.md
        - Tăng trưởng: ecology/energy/human-ambition/1-growth.md
        - Kinh tế: ecology/energy/human-ambition/2-econ.md
        - Dân số: ecology/energy/human-ambition/3-population.md
      - Năng lượng tái tạo: ecology/energy/renewable-skeptics.md

theme: 
  name: material
  language: en
  font:
    # text: Source Serif Pro
    # text: Playfair Display
    # text: Noto Serif
    text: Literata
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - search.highlight
    # - search.share
    - search.suggest
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.bottom
    - navigation.tracking
    - navigation.expand
    - toc.follow

extra_css: [stylesheets/extra.css]

copyright: Copyright &copy; 2023 Sustainable Living

extra:
  generator: false
  # consent:
  #   actions:
  #     - accept
  #     - manage

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search:
      lang: 
        - en

watch:
  - .  # reload docs for any file changes
